// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dastanchynybek/rag-chat/backend/internal/repository (interfaces: UserRepository,DocumentRepository,ChunkRepository,ChatRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_repositories.go -package=mocks github.com/dastanchynybek/rag-chat/backend/internal/repository UserRepository,DocumentRepository,ChunkRepository,ChatRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dastanchynybek/rag-chat/backend/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockDocumentRepository is a mock of DocumentRepository interface.
type MockDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockDocumentRepositoryMockRecorder is the mock recorder for MockDocumentRepository.
type MockDocumentRepositoryMockRecorder struct {
	mock *MockDocumentRepository
}

// NewMockDocumentRepository creates a new mock instance.
func NewMockDocumentRepository(ctrl *gomock.Controller) *MockDocumentRepository {
	mock := &MockDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentRepository) EXPECT() *MockDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentRepository) Create(ctx context.Context, doc *model.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDocumentRepositoryMockRecorder) Create(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentRepository)(nil).Create), ctx, doc)
}

// Delete mocks base method.
func (m *MockDocumentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDocumentRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDocumentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDocumentRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockDocumentRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]model.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockDocumentRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockDocumentRepository)(nil).ListByUser), ctx, userID)
}

// UpdateChunkCount mocks base method.
func (m *MockDocumentRepository) UpdateChunkCount(ctx context.Context, id uuid.UUID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChunkCount", ctx, id, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChunkCount indicates an expected call of UpdateChunkCount.
func (mr *MockDocumentRepositoryMockRecorder) UpdateChunkCount(ctx, id, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChunkCount", reflect.TypeOf((*MockDocumentRepository)(nil).UpdateChunkCount), ctx, id, count)
}

// MockChunkRepository is a mock of ChunkRepository interface.
type MockChunkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChunkRepositoryMockRecorder
	isgomock struct{}
}

// MockChunkRepositoryMockRecorder is the mock recorder for MockChunkRepository.
type MockChunkRepositoryMockRecorder struct {
	mock *MockChunkRepository
}

// NewMockChunkRepository creates a new mock instance.
func NewMockChunkRepository(ctrl *gomock.Controller) *MockChunkRepository {
	mock := &MockChunkRepository{ctrl: ctrl}
	mock.recorder = &MockChunkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkRepository) EXPECT() *MockChunkRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockChunkRepository) CreateBatch(ctx context.Context, chunks []model.Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockChunkRepositoryMockRecorder) CreateBatch(ctx, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockChunkRepository)(nil).CreateBatch), ctx, chunks)
}

// DeleteByDocument mocks base method.
func (m *MockChunkRepository) DeleteByDocument(ctx context.Context, documentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDocument", ctx, documentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByDocument indicates an expected call of DeleteByDocument.
func (mr *MockChunkRepositoryMockRecorder) DeleteByDocument(ctx, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDocument", reflect.TypeOf((*MockChunkRepository)(nil).DeleteByDocument), ctx, documentID)
}

// SearchSimilar mocks base method.
func (m *MockChunkRepository) SearchSimilar(ctx context.Context, embedding []float32, userID uuid.UUID, limit int, threshold float64) ([]model.ChunkWithDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSimilar", ctx, embedding, userID, limit, threshold)
	ret0, _ := ret[0].([]model.ChunkWithDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSimilar indicates an expected call of SearchSimilar.
func (mr *MockChunkRepositoryMockRecorder) SearchSimilar(ctx, embedding, userID, limit, threshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSimilar", reflect.TypeOf((*MockChunkRepository)(nil).SearchSimilar), ctx, embedding, userID, limit, threshold)
}

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
	isgomock struct{}
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockChatRepository) CreateMessage(ctx context.Context, msg *model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockChatRepositoryMockRecorder) CreateMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockChatRepository)(nil).CreateMessage), ctx, msg)
}

// CreateSession mocks base method.
func (m *MockChatRepository) CreateSession(ctx context.Context, session *model.ChatSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockChatRepositoryMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockChatRepository)(nil).CreateSession), ctx, session)
}

// GetMessagesBySession mocks base method.
func (m *MockChatRepository) GetMessagesBySession(ctx context.Context, sessionID uuid.UUID) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBySession", ctx, sessionID)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBySession indicates an expected call of GetMessagesBySession.
func (mr *MockChatRepositoryMockRecorder) GetMessagesBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBySession", reflect.TypeOf((*MockChatRepository)(nil).GetMessagesBySession), ctx, sessionID)
}

// GetSession mocks base method.
func (m *MockChatRepository) GetSession(ctx context.Context, id uuid.UUID) (*model.ChatSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*model.ChatSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockChatRepositoryMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockChatRepository)(nil).GetSession), ctx, id)
}

// ListSessionsByUser mocks base method.
func (m *MockChatRepository) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]model.ChatSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUser", ctx, userID)
	ret0, _ := ret[0].([]model.ChatSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUser indicates an expected call of ListSessionsByUser.
func (mr *MockChatRepositoryMockRecorder) ListSessionsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUser", reflect.TypeOf((*MockChatRepository)(nil).ListSessionsByUser), ctx, userID)
}

// UpdateSessionTitle mocks base method.
func (m *MockChatRepository) UpdateSessionTitle(ctx context.Context, id uuid.UUID, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionTitle", ctx, id, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionTitle indicates an expected call of UpdateSessionTitle.
func (mr *MockChatRepositoryMockRecorder) UpdateSessionTitle(ctx, id, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionTitle", reflect.TypeOf((*MockChatRepository)(nil).UpdateSessionTitle), ctx, id, title)
}
