// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dastanchynybek/rag-chat/backend/internal/pkg/llm (interfaces: LLMClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_llm.go -package=mocks github.com/dastanchynybek/rag-chat/backend/internal/pkg/llm LLMClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	llm "github.com/dastanchynybek/rag-chat/backend/internal/pkg/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// ChatStream mocks base method.
func (m *MockLLMClient) ChatStream(ctx context.Context, messages []llm.ChatMessage) (<-chan string, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, messages)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockLLMClientMockRecorder) ChatStream(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockLLMClient)(nil).ChatStream), ctx, messages)
}

// Embed mocks base method.
func (m *MockLLMClient) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, texts)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockLLMClientMockRecorder) Embed(ctx, texts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockLLMClient)(nil).Embed), ctx, texts)
}
